///strings by english
abstract class StringsEn {
  static const String language = 'language';
  static const String appName = 'Charity Clothes';
  static const String English = 'English';
  static const String Arabic = 'Arabic';
  static const String donateClothes = 'Donate clothes';
  static const String phoneNumber = 'phone Number';
  static const String name = 'name';
  static const String login = 'Login';
  static const String selectCountry = 'Select Country';
  static const String enterAddressDetails = 'Enter address details';
  static const String submit = 'Submit';
  static const String numberOfPieces = 'Number of pieces';
  static const String address = 'Address';
  static const String deliveryTime = 'delivery time';
  static const String deliveryDate = 'delivery date';
  static const String otp = 'Otp';
  static const String dateFormat = 'yyyy-MM-dd';
  static const String fromGallery = 'from Gallery';
  static const String fromCamera = 'from Camera';
  static const String apartmentNumber = 'Apartment number';
  static const String specialMarque = 'special marque';
  static const String addresSDetail = 'Enter the address in detail';
  static const String confirmAddress = 'Confirm address';
  static const String confirmed = "Confirmed";
  static const String validator = "I'm from validator";
  static const String track = "Track";
  static const String cancel = "Cancel";
  static const String details = "Details";
  static const String status = 'Status';
  static const String date = 'Date';
  static const String dontReceiveCode = "Didn't receive the code? ";
  static const String ourPlan = 'Our plan';
  static const String orderTrack = 'order track';
  static const String home = 'Home';
  static const String connectUs = 'Connect us';
  static const String resend = 'Resend';
  static const String customerName = 'customer name';
  static const String messeges = 'messeges';
  static const String noMesseges = ' No messeges';
  static const String orderDetails = ' Order details';
  static const String enterPhone = 'Enter phone number';
  static const String socialNetwork = 'Social network';
  static const String deleteAccount = 'Delete Account';
  static const String feedback = 'Feedback';
  static const String overVision = 'Over vision';
  static const String noConnection = 'No Internet';
  static const String code = '+20';
  static const String verify = 'Verify Otp';
  static const String verId = 'verification id';
  static const String signOut = 'Sign out';
  static const String questionLang =
      "Are you sure you want to change Language?";
  static const String id = 'id';
  static const String vision =
      'Our vision is based on the satisfaction of our dear donors and improving their experience by providing the best way to communicate with ease and at the level of the Hashemite Kingdom of Jordan only, so everything we plan for in our future strategic plans focuses on achieving this goal.';
  static const String plan =
      'And because Charity clothes is for the people and for the people, we seek through our new vision and goals to contribute significantly to raising the standard of living in the community and the region. Believing that the stability of our work today is the growth and prosperity of the region tomorrow. We are keen to be the name you can always rely on.';
  static const String phoneNum = '01023412234';
  static const String facebook =
      'https://www.facebook.com/taher.amen.562?locale=ar_AR';
  static const String gmail = 'tataamen678@gmail.com';
  static const String instgram = 'https://www.instagram.com/';
  static const String twitter =
      'https://twitter.com/Ta7er2?t=jYG03ucx0EGWtZzNls1O-g&s=09';
  static const String no = 'No';
  static const String yes = 'Yes';
  static const String doYouWantDeleteAcccount ='Do you Want To Delete The Account?';
  static const String ok ='sure';
  static const String doYouWantSignOut ='Do you Want To Sign out?';
  static const String weNeedToVerifyYourNumberFirst ='We need to verify your number first.You will receive the OTP once you click Submit';
  static const String someThingOccur='something occurred';
  static const String accountDeletedSuccessfully='Account Deleted Successful';
  static const String signoutSuccess='Signout Success';
  static const String successfulDeleted='Successful deleted';
  static const String enterTheCorrectInfo='Please, Enter the correct information!';
  static const String enterYourPosition='Please ,Enter your position!';
  static const String thankYouForDonation='Thank you for your donation';
  static const String providedNumIsNotValid='The provided phone number is not valid.';
  static const String success="Success";
  static const String error="Error";
  static const String warning="Warning";
  static const String information="Information";
}

///strings by arabic
abstract class StringsAr {
  static const String appName = 'Charity Clothes';
  static const String donateClothes = 'تبرع بالملابس';
  static const String phoneNumber = 'رقم الهاتف';
  static const String name = 'الاسم';
  static const String login = 'دخول';
  static const String selectCountry = 'رقم الدوله';
  static const String enterAddressDetails = 'ادخل العنوان بالتفصيل';
  static const String submit = 'ارسال';
  static const String numberOfPieces = 'عدد القطع';
  static const String address = 'العنوان';
  static const String deliveryTime = 'وقت التسليم';
  static const String deliveryDate = 'تاريخ التسليم';
  static const String dateFormat = 'yyyy-MM-dd';
  static const String fromGallery = 'من الهاتف';
  static const String fromCamera = 'من الكاميرا';
  static const String apartmentNumber = 'رقم الشقه';
  static const String specialMarque = 'علامه مميزه';
  static const String addresSDetail = 'ادخل العنوان بالتفصيل';
  static const String confirmAddress = ' تأكيد العنوان';
  static const String confirmed = "تم التسليم";
  static const String validator = "غير متاح";
  static const String track = "تتبع";
  static const String cancel = "الغاء";
  static const String details = "التفاصيل";
  static const String status = 'الحاله';
  static const String date = 'التاريخ';
  static const String dontReceiveCode = "لم تستلم الرمز؟";
  static const String resend = "اعادة ارسال";
  static const String ourPlan = 'خطتنا';
  static const String orderTrack = 'تتبع الطلب';
  static const String home = 'الرئيسيه';
  static const String connectUs = 'اتصل بنا';
  static const String customerName = 'اسم العميل';
  static const String messeges = 'الرسائل';
  static const String noMesseges = 'لا توجد رسائل';
  static const String orderDetails = 'تفاصيل الطلب';
  static const String enterPhone = 'ادخل رقم الهاتف';
  static const String socialNetwork = 'مواقع التواصل';
  static const String deleteAccount = 'حذف الحساب';
  static const String signOut = 'تسجيل خروج';
  static const String feedback = 'تعليق';
  static const String overVision = 'هدفنا';
  static const String questionLang = "هل انت متأكد من تغير لغة الجهاز؟";
  static const String noConnection = 'غير متصل بالانترنت';
  static const String code = '+20';
  static const String otp = 'رمز التأكيد';
  static const String no = 'لا';
  static const String yes = 'نعم';
  static const String verify = 'تأكيد المستخدم';
  static const String vision =
      'رؤيتنا مبنية على رضاء المتبرعين الأعزاء وتحسين تجربتهم من خلال توفير أفضل وسيلة للتواصل بكل سهولة وعلى مستوى المملكة الأردنية الهاشمية فقط، لذلك يركز كل ما نخطط له في خططنا الإستراتيجية المستقبلية على تحقيق هذا الهدف.';
  static const String plan =
      'ولأن الملابس الخيرية هي للشعب وللناس، فإننا نسعى من خلال رؤيتنا وأهدافنا الجديدة إلى المساهمة بشكل كبير في رفع مستوى المعيشة في المجتمع والمنطقة. إيماناً منا بأن استقرار عملنا اليوم هو نمو وازدهار المنطقة غداً. نحن حريصون على أن نكون الاسم الذي يمكنك الاعتماد عليه دائمًا';
  static const String doYouWantDeleteAcccount ='هل تريد ازالة الحساب الخاص بك؟';
  static const String ok ='بالتأكيد';
  static const String doYouWantSignOut ='هل تريد تسجيل الخروج؟';
  static const String weNeedToVerifyYourNumberFirst ='نحتاج إلى التحقق من رقمك أولاً. سوف تتلقى كلمة المرور لمرة واحدة (OTP) بمجرد النقر فوق "إرسال".';
  static const String someThingOccur='حدث خطأ';
  static const String accountDeletedSuccessfully='تم ازالة الحساب';
  static const String signoutSuccess='تم تسجيل الخروج';
  static const String successfulDeleted='تم الازاله بنجاح';
  static const String enterTheCorrectInfo='من فضلك، أدخل المعلومات الصحيحة!';
  static const String enterYourPosition='من فضلك، أدخل موقعك!';
  static const String thankYouForDonation='شكرا لك على تبرعك';
  static const String providedNumIsNotValid='رقم الهاتف  غير صالح.';
  static const String success="تم بنجاح";
  static const String error="خطأ";
  static const String warning="تحذير";
  static const String information="معلومة";

}
